import 'package:flutter/material.dart';
import 'data.dart';
void main() {
  runApp(const Lavel1());
}

// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class Lavel1 extends StatelessWidget {
  const Lavel1({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: const Color.fromARGB(255, 18, 32, 47),
      ),
      home: Scaffold(
        body: ListView(children: [
          Lavel(),
        ]),
      ),
    );
  }
}

class Lavel extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Container(
          width: 375,
          height: 812,
          clipBehavior: Clip.antiAlias,
          decoration: BoxDecoration(color: Colors.white),
          child: Stack(
            children: [
              Align(
          alignment: Alignment.topLeft,
          
          child: Padding(
            padding: const EdgeInsets.all(15.0),
            child: ElevatedButton(
              onPressed: () {
                    Navigator.push(
                      context,
                      MaterialPageRoute(builder: (context) => Data1()),
                    );
                  },
              child: const Text('이전'),
            ),
          ),
        ),
              Positioned(
                left: 17,
                top: 511,
                child: Container(
                  height: 104,
                  child: Column(
                    mainAxisSize: MainAxisSize.min,
                    mainAxisAlignment: MainAxisAlignment.center,
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      SizedBox(
                        
                        child: Text(
                          'b',
                          style: TextStyle(
                            color: Colors.black,
                            fontSize: 15,
                            fontFamily: 'Inter',
                            fontWeight: FontWeight.w600,
                            height: 1,
                          ),
                        ),
                      ),
                      const SizedBox(height: 15),
                      SizedBox(
                        
                        child: Text(
                          '낱개의 고르기 : 크기 구분표에서 무게가 다른 것이 5% 이하인것. 단, 크기 구분표의 해당 무게에서 1단계를 초과 할 수 없다\n색택 : 착색 비율표에서 정하는 [상]에 미달 하는 것이 없는 것. 단 쓰가루(비착색계)는 적용하지 않는다\n신선도 : 껍질의 수축현상이 나타나지 않은 것\n중결점과 : 없는 것\n경결점과 : 10% 이하인 것',
                          style: TextStyle(
                            color: Color(0xFF828282),
                            fontSize: 8,
                            fontFamily: 'Inter',
                            fontWeight: FontWeight.w400,
                            height: 1,
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 17,
                top: 397,
                child: Container(
                  height: 92,
                  child: Column(
                    mainAxisSize: MainAxisSize.min,
                    mainAxisAlignment: MainAxisAlignment.center,
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      SizedBox(
                        
                        child: Text(
                          'A',
                          style: TextStyle(
                            color: Colors.black,
                            fontSize: 15,
                            fontFamily: 'Inter',
                            fontWeight: FontWeight.w600,
                            height: 1,
                          ),
                        ),
                      ),
                      const SizedBox(height: 15),
                      SizedBox(
                       
                        child: Text(
                          '낱개의 고르기 : 크기 구분표에서 무게가 다른 것이 섞이지 않은 것\n색택 : 착색 비율표에서 정하는 [특]이외의 것이 섞이지 않은 것. 단 쓰가루(비착색계)는 적용하지 않는다\n신선도 : 윤기가 나고 껍질의 수축현상이 나타나지 않은 것\n중결점과 : 없는 것\n경결점과 : 없는 것',
                          style: TextStyle(
                            color: Color(0xFF828282),
                            fontSize: 8,
                            fontFamily: 'Inter',
                            fontWeight: FontWeight.w400,
                            height: 1,
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 17,
                top: 637,
                child: Container(
                  height: 92,
                  child: Column(
                    mainAxisSize: MainAxisSize.min,
                    mainAxisAlignment: MainAxisAlignment.center,
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      SizedBox(
                       
                        child: Text(
                          'c',
                          style: TextStyle(
                            color: Colors.black,
                            fontSize: 15,
                            fontFamily: 'Inter',
                            fontWeight: FontWeight.w600,
                            height: 1,
                          ),
                        ),
                      ),
                      const SizedBox(height: 15),
                      SizedBox(
                      
                        child: Text(
                          '낱개의 고르기 : 특,상에 미달하는 것\n색택 : 착색 비율표에서 정하는 [보통]에 미달 하는 것이 없는 것\n신선도 : 특,상에 미달하는 것\n중결점과 : 5% 이하인 것(부패,변질과는 포함할 수 없다)\n경결점과 : 20% 이하인 것',
                          style: TextStyle(
                            color: Color(0xFF828282),
                            fontSize: 8,
                            fontFamily: 'Inter',
                            fontWeight: FontWeight.w400,
                            height: 1,
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 17,
                top: 265,
                child: Container(
                  width: 342,
                  height: 110,
                  clipBehavior: Clip.antiAlias,
                  decoration: ShapeDecoration(
                    color: Colors.white,
                    shape: RoundedRectangleBorder(
                      side: BorderSide(width: 1, color: Color(0xFFB9B9B9)),
                      borderRadius: BorderRadius.circular(4),
                    ),
                  ),
                  child: Column(

                    children: [
                      Container(
                        
                        height: 24,
                        clipBehavior: Clip.antiAlias,
                        decoration: BoxDecoration(
                          color: Colors.white.withOpacity(0.00009999999747378752),
                        ),
                        child: Row(
                          
                          children: [
                            Expanded(
                              child: Container(
                                
                                decoration: BoxDecoration(
                                  color: Colors.black.withOpacity(0.05999999865889549),
                                  border: Border(
                                    left: BorderSide(width: 1, color: Color(0xFFB9B9B9)),
                                    top: BorderSide(width: 1, color: Color(0xFFB9B9B9)),
                                    right: BorderSide(color: Color(0xFFB9B9B9)),
                                    bottom: BorderSide(color: Color(0xFFB9B9B9)),
                                  ),
                                ),
                                child: Column(
                                  mainAxisSize: MainAxisSize.min,
                                  mainAxisAlignment: MainAxisAlignment.start,
                                  crossAxisAlignment: CrossAxisAlignment.start,
                                  children: [
                                    Expanded(
                                      child: Container(
                              
                                        padding: const EdgeInsets.symmetric(horizontal: 12, vertical: 10),
                                        clipBehavior: Clip.antiAlias,
                                        decoration: BoxDecoration(),
                                        child: Row(
                                          
                                          children: [
                                            Expanded(
                                              child: SizedBox(
                                               
                                                child: Text.rich(
                                                  TextSpan(),
                                                ),
                                              ),
                                            ),
                                          ],
                                        ),
                                      ),
                                    ),
                                  ],
                                ),
                              ),
                            ),
                            Expanded(
                              child: Container(
                              
                                decoration: BoxDecoration(
                                  color: Colors.black.withOpacity(0.05999999865889549),
                                  border: Border(
                                    left: BorderSide(width: 1, color: Color(0xFFB9B9B9)),
                                    top: BorderSide(width: 1, color: Color(0xFFB9B9B9)),
                                    right: BorderSide(color: Color(0xFFB9B9B9)),
                                    bottom: BorderSide(color: Color(0xFFB9B9B9)),
                                  ),
                                ),
                                  child: Column(
                                    mainAxisSize: MainAxisSize.min,
                                    mainAxisAlignment: MainAxisAlignment.start,
                                    crossAxisAlignment: CrossAxisAlignment.start,
                                    children: [
                                      Expanded(
                                        child: Container(
                              
                                          
                                          clipBehavior: Clip.antiAlias,
                                          decoration: BoxDecoration(),
                                          child: Row(
                                            
                                            children: [
                                              Expanded(
                                                child: SizedBox(
                                              
                                                  child: Text(
                                                    '특',
                                                    textAlign: TextAlign.center,
                                                    style: TextStyle(
                                                      color: Colors.black,
                                                      fontSize: 7,
                                                      fontFamily: 'Inter',
                                                      fontWeight: FontWeight.w600,
                                                      height: 1,
                                                    ),
                                                  ),
                                                ),
                                              ),
                                            ],
                                          ),
                                        ),
                                      ),
                                    ],
                                  ),
                                ),
                              ),
                            Expanded(
                              child: Container(
                             
                                decoration: BoxDecoration(
                                  color: Colors.black.withOpacity(0.05999999865889549),
                                  border: Border(
                                    left: BorderSide(width: 1, color: Color(0xFFB9B9B9)),
                                    top: BorderSide(width: 1, color: Color(0xFFB9B9B9)),
                                    right: BorderSide(color: Color(0xFFB9B9B9)),
                                    bottom: BorderSide(color: Color(0xFFB9B9B9)),
                                  ),
                                ),
                                child: Column(
                                  mainAxisSize: MainAxisSize.min,
                                  mainAxisAlignment: MainAxisAlignment.start,
                                  crossAxisAlignment: CrossAxisAlignment.start,
                                  children: [
                                    Expanded(
                                      child: Container(
                                     
                                        
                                        clipBehavior: Clip.antiAlias,
                                        decoration: BoxDecoration(),
                                        child: Row(
                                          
                                          children: [
                                            Expanded(
                                              child: SizedBox(
                                             
                                                child: Text(
                                                  '상',
                                                  textAlign: TextAlign.center,
                                                  style: TextStyle(
                                                    color: Colors.black,
                                                    fontSize: 7,
                                                    fontFamily: 'Inter',
                                                    fontWeight: FontWeight.w600,
                                                    height: 1,
                                                  ),
                                                ),
                                              ),
                                            ),
                                          ],
                                        ),
                                      ),
                                    ),
                                  ],
                                ),
                              ),
                            ),
                            Expanded(
                              child: Container(
                              
                                decoration: BoxDecoration(
                                  color: Colors.black.withOpacity(0.05999999865889549),
                                  border: Border(
                                    left: BorderSide(width: 1, color: Color(0xFFB9B9B9)),
                                    top: BorderSide(width: 1, color: Color(0xFFB9B9B9)),
                                    right: BorderSide(color: Color(0xFFB9B9B9)),
                                    bottom: BorderSide(color: Color(0xFFB9B9B9)),
                                  ),
                                ),
                                child: Column(
                                  mainAxisSize: MainAxisSize.min,
                                  mainAxisAlignment: MainAxisAlignment.start,
                                  crossAxisAlignment: CrossAxisAlignment.start,
                                  children: [
                                    Expanded(
                                      child: Container(
                                    
                                        
                                        clipBehavior: Clip.antiAlias,
                                        decoration: BoxDecoration(),
                                        child: Row(
                                          
                                          children: [
                                            Expanded(
                                              child: SizedBox(
                                           
                                                child: Text(
                                                  '보통',
                                                  textAlign: TextAlign.center,
                                                  style: TextStyle(
                                                    color: Colors.black,
                                                    fontSize: 7,
                                                    fontFamily: 'Inter',
                                                    fontWeight: FontWeight.w600,
                                                    height: 1,
                                                  ),
                                                ),
                                              ),
                                            ),
                                          ],
                                        ),
                                      ),
                                    ),
                                  ],
                                ),
                              ),
                            ),
                          ],
                        ),
                      ),
                      Expanded(
                        child: Container(
                        
                          clipBehavior: Clip.antiAlias,
                          decoration: BoxDecoration(
                            color: Colors.white.withOpacity(0.00009999999747378752),
                          ),
                          child: Row(
                            
                            children: [
                              Expanded(
                                child: Container(
                                
                                  decoration: BoxDecoration(
                                    color: Colors.white.withOpacity(0.0020000000949949026),
                                    border: Border(
                                      left: BorderSide(width: 1, color: Color(0xFFB9B9B9)),
                                      top: BorderSide(width: 1, color: Color(0xFFB9B9B9)),
                                      right: BorderSide(color: Color(0xFFB9B9B9)),
                                      bottom: BorderSide(color: Color(0xFFB9B9B9)),
                                    ),
                                  ),
                                  child: Column(
                                    mainAxisSize: MainAxisSize.min,
                                    mainAxisAlignment: MainAxisAlignment.start,
                                    crossAxisAlignment: CrossAxisAlignment.start,
                                    children: [
                                      Expanded(
                                        child: Container(
                                      
                                          padding: const EdgeInsets.symmetric(horizontal: 12, vertical: 10),
                                          clipBehavior: Clip.antiAlias,
                                          decoration: BoxDecoration(),
                                          child: Row(
                                            mainAxisSize: MainAxisSize.min,
                                            mainAxisAlignment: MainAxisAlignment.start,
                                            crossAxisAlignment: CrossAxisAlignment.start,
                                            children: [
                                              Expanded(
                                                child: SizedBox(
                            
                                                  child: Text(
                                                    '홍옥, 홍로, 화홍,  양광 및 이와 유사한 품종',
                                                    style: TextStyle(
                                                      color: Colors.black,
                                                      fontSize: 5,
                                                      fontFamily: 'Inter',
                                                      fontWeight: FontWeight.w400,
                                                      height: 1,
                                                    ),
                                                  ),
                                                ),
                                              ),
                                            ],
                                          ),
                                        ),
                                      ),
                                    ],
                                  ),
                                ),
                              ),
                              Expanded(
                                child: Container(
                           
                                  decoration: BoxDecoration(
                                    color: Colors.white.withOpacity(0.0020000000949949026),
                                    border: Border(
                                      left: BorderSide(width: 1, color: Color(0xFFB9B9B9)),
                                      top: BorderSide(width: 1, color: Color(0xFFB9B9B9)),
                                      right: BorderSide(color: Color(0xFFB9B9B9)),
                                      bottom: BorderSide(color: Color(0xFFB9B9B9)),
                                    ),
                                  ),
                                  child: Column(
                                    mainAxisSize: MainAxisSize.min,
                                    mainAxisAlignment: MainAxisAlignment.start,
                                    crossAxisAlignment: CrossAxisAlignment.start,
                                    children: [
                                      Expanded(
                                        child: Container(
                                     
                                          padding: const EdgeInsets.symmetric(horizontal: 12, vertical: 10),
                                          clipBehavior: Clip.antiAlias,
                                          decoration: BoxDecoration(),
                                          child: Row(
                                            mainAxisSize: MainAxisSize.min,
                                            mainAxisAlignment: MainAxisAlignment.start,
                                            crossAxisAlignment: CrossAxisAlignment.start,
                                            children: [
                                              Expanded(
                                                child: SizedBox(
                                            
                                                  child: Text(
                                                    '70% 이상',
                                                    textAlign: TextAlign.center,
                                                    style: TextStyle(
                                                      color: Colors.black,
                                                      fontSize: 5,
                                                      fontFamily: 'Inter',
                                                      fontWeight: FontWeight.w400,
                                                      height: 1,
                                                    ),
                                                  ),
                                                ),
                                              ),
                                            ],
                                          ),
                                        ),
                                      ),
                                    ],
                                  ),
                                ),
                              ),
                              Expanded(
                                child: Container(
                           
                                  decoration: BoxDecoration(
                                    color: Colors.white.withOpacity(0.0020000000949949026),
                                    border: Border(
                                      left: BorderSide(width: 1, color: Color(0xFFB9B9B9)),
                                      top: BorderSide(width: 1, color: Color(0xFFB9B9B9)),
                                      right: BorderSide(color: Color(0xFFB9B9B9)),
                                      bottom: BorderSide(color: Color(0xFFB9B9B9)),
                                    ),
                                  ),
                                  child: Column(
                                    mainAxisSize: MainAxisSize.min,
                                    mainAxisAlignment: MainAxisAlignment.start,
                                    crossAxisAlignment: CrossAxisAlignment.start,
                                    children: [
                                      Expanded(
                                        child: Container(
                                 
                                          padding: const EdgeInsets.symmetric(horizontal: 12, vertical: 10),
                                          clipBehavior: Clip.antiAlias,
                                          decoration: BoxDecoration(),
                                          child: Row(
                                            mainAxisSize: MainAxisSize.min,
                                            mainAxisAlignment: MainAxisAlignment.start,
                                            crossAxisAlignment: CrossAxisAlignment.start,
                                            children: [
                                              Expanded(
                                                child: SizedBox(
                                           
                                                  child: Text(
                                                    '50% 이상',
                                                    textAlign: TextAlign.center,
                                                    style: TextStyle(
                                                      color: Colors.black,
                                                      fontSize: 5,
                                                      fontFamily: 'Inter',
                                                      fontWeight: FontWeight.w400,
                                                      height: 1,
                                                    ),
                                                  ),
                                                ),
                                              ),
                                            ],
                                          ),
                                        ),
                                      ),
                                    ],
                                  ),
                                ),
                              ),
                              Expanded(
                                child: Container(
                              
                                  decoration: BoxDecoration(
                                    color: Colors.white.withOpacity(0.0020000000949949026),
                                    border: Border(
                                      left: BorderSide(width: 1, color: Color(0xFFB9B9B9)),
                                      top: BorderSide(width: 1, color: Color(0xFFB9B9B9)),
                                      right: BorderSide(color: Color(0xFFB9B9B9)),
                                      bottom: BorderSide(color: Color(0xFFB9B9B9)),
                                    ),
                                  ),
                                  child: Column(
                                    mainAxisSize: MainAxisSize.min,
                                    mainAxisAlignment: MainAxisAlignment.start,
                                    crossAxisAlignment: CrossAxisAlignment.start,
                                    children: [
                                      Expanded(
                                        child: Container(
                                          padding: const EdgeInsets.symmetric(horizontal: 12, vertical: 10),
                                          clipBehavior: Clip.antiAlias,
                                          decoration: BoxDecoration(),
                                          child: Row(
                                            mainAxisSize: MainAxisSize.min,
                                            mainAxisAlignment: MainAxisAlignment.start,
                                            crossAxisAlignment: CrossAxisAlignment.start,
                                            children: [
                                              Expanded(
                                                child: SizedBox(
                                                  child: Text(
                                                    '30% 이상',
                                                    textAlign: TextAlign.center,
                                                    style: TextStyle(
                                                      color: Colors.black,
                                                      fontSize: 5,
                                                      fontFamily: 'Inter',
                                                      fontWeight: FontWeight.w400,
                                                      height: 1,
                                                    ),
                                                  ),
                                                ),
                                              ),
                                            ],
                                          ),
                                        ),
                                      ),
                                    ],
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                      Expanded(
                        child: Container(
                          clipBehavior: Clip.antiAlias,
                          decoration: BoxDecoration(
                            color: Colors.white.withOpacity(0.00009999999747378752),
                          ),
                          child: Row(
                            mainAxisSize: MainAxisSize.min,
                            mainAxisAlignment: MainAxisAlignment.start,
                            crossAxisAlignment: CrossAxisAlignment.start,
                            children: [
                              Expanded(
                                child: Container(
                                  decoration: BoxDecoration(
                                    color: Colors.white.withOpacity(0.0020000000949949026),
                                    border: Border(
                                      left: BorderSide(width: 1, color: Color(0xFFB9B9B9)),
                                      top: BorderSide(width: 1, color: Color(0xFFB9B9B9)),
                                      right: BorderSide(color: Color(0xFFB9B9B9)),
                                      bottom: BorderSide(color: Color(0xFFB9B9B9)),
                                    ),
                                  ),
                                  child: Column(
                                    mainAxisSize: MainAxisSize.min,
                                    mainAxisAlignment: MainAxisAlignment.start,
                                    crossAxisAlignment: CrossAxisAlignment.start,
                                    children: [
                                      Container(
                                        padding: const EdgeInsets.symmetric(horizontal: 8, vertical:4),
                                        clipBehavior: Clip.antiAlias,
                                        decoration: BoxDecoration(),
                                        child: Row(
                                          mainAxisSize: MainAxisSize.min,
                                          mainAxisAlignment: MainAxisAlignment.start,
                                          crossAxisAlignment: CrossAxisAlignment.start,
                                          children: [
                                            Expanded(
                                              child: SizedBox(
                                                child: Text(
                                                  '후지, 조나골드, 세계일, 추광, 서광, 선홍, 새나라 및 이와 유사한 품종',
                                                  style: TextStyle(
                                                    color: Colors.black,
                                                    fontSize: 5,
                                                    fontFamily: 'Inter',
                                                    fontWeight: FontWeight.w400,
                                                    height: 1,
                                                  ),
                                                ),
                                              ),
                                            ),
                                          ],
                                        ),
                                      ),
                                    ],
                                  ),
                                ),
                              ),
                              Expanded(
                                child: Container(
                                  decoration: BoxDecoration(
                                    color: Colors.white.withOpacity(0.0020000000949949026),
                                    border: Border(
                                      left: BorderSide(width: 1, color: Color(0xFFB9B9B9)),
                                      top: BorderSide(width: 1, color: Color(0xFFB9B9B9)),
                                      right: BorderSide(color: Color(0xFFB9B9B9)),
                                      bottom: BorderSide(color: Color(0xFFB9B9B9)),
                                    ),
                                  ),
                                  child: Column(
                                    mainAxisSize: MainAxisSize.min,
                                    mainAxisAlignment: MainAxisAlignment.start,
                                    crossAxisAlignment: CrossAxisAlignment.start,
                                    children: [
                                      Expanded(
                                        child: Container(
                                          padding: const EdgeInsets.symmetric(horizontal: 12, vertical: 10),
                                          clipBehavior: Clip.antiAlias,
                                          decoration: BoxDecoration(),
                                          child: Row(
                                            mainAxisSize: MainAxisSize.min,
                                            mainAxisAlignment: MainAxisAlignment.start,
                                            crossAxisAlignment: CrossAxisAlignment.start,
                                            children: [
                                              Expanded(
                                                child: SizedBox(
                                                  child: Text(
                                                    '60% 이상',
                                                    textAlign: TextAlign.center,
                                                    style: TextStyle(
                                                      color: Colors.black,
                                                      fontSize: 5,
                                                      fontFamily: 'Inter',
                                                      fontWeight: FontWeight.w400,
                                                      height: 1,
                                                    ),
                                                  ),
                                                ),
                                              ),
                                            ],
                                          ),
                                        ),
                                      ),
                                    ],
                                  ),
                                ),
                              ),
                              Expanded(
                                child: Container(
                                  decoration: BoxDecoration(
                                    color: Colors.white.withOpacity(0.0020000000949949026),
                                    border: Border(
                                      left: BorderSide(width: 1, color: Color(0xFFB9B9B9)),
                                      top: BorderSide(width: 1, color: Color(0xFFB9B9B9)),
                                      right: BorderSide(color: Color(0xFFB9B9B9)),
                                      bottom: BorderSide(color: Color(0xFFB9B9B9)),
                                    ),
                                  ),
                                  child: Column(
                                    mainAxisSize: MainAxisSize.min,
                                    mainAxisAlignment: MainAxisAlignment.start,
                                    crossAxisAlignment: CrossAxisAlignment.start,
                                    children: [
                                      Expanded(
                                        child: Container(
                                          padding: const EdgeInsets.symmetric(horizontal: 12, vertical: 10),
                                          clipBehavior: Clip.antiAlias,
                                          decoration: BoxDecoration(),
                                          child: Row(
                                            mainAxisSize: MainAxisSize.min,
                                            mainAxisAlignment: MainAxisAlignment.start,
                                            crossAxisAlignment: CrossAxisAlignment.start,
                                            children: [
                                              Expanded(
                                                child: SizedBox(
                                                  child: Text(
                                                    '40% 이상',
                                                    textAlign: TextAlign.center,
                                                    style: TextStyle(
                                                      color: Colors.black,
                                                      fontSize: 5,
                                                      fontFamily: 'Inter',
                                                      fontWeight: FontWeight.w400,
                                                      height: 1,
                                                    ),
                                                  ),
                                                ),
                                              ),
                                            ],
                                          ),
                                        ),
                                      ),
                                    ],
                                  ),
                                ),
                              ),
                              Expanded(
                                child: Container(
                                  decoration: BoxDecoration(
                                    color: Colors.white.withOpacity(0.0020000000949949026),
                                    border: Border(
                                      left: BorderSide(width: 1, color: Color(0xFFB9B9B9)),
                                      top: BorderSide(width: 1, color: Color(0xFFB9B9B9)),
                                      right: BorderSide(color: Color(0xFFB9B9B9)),
                                      bottom: BorderSide(color: Color(0xFFB9B9B9)),
                                    ),
                                  ),
                                  child: Column(
                                    mainAxisSize: MainAxisSize.min,
                                    mainAxisAlignment: MainAxisAlignment.start,
                                    crossAxisAlignment: CrossAxisAlignment.start,
                                    children: [
                                      Expanded(
                                        child: Container(
                                          padding: const EdgeInsets.symmetric(horizontal: 12, vertical: 10),
                                          clipBehavior: Clip.antiAlias,
                                          decoration: BoxDecoration(),
                                          child: Row(
                                            mainAxisSize: MainAxisSize.min,
                                            mainAxisAlignment: MainAxisAlignment.start,
                                            crossAxisAlignment: CrossAxisAlignment.start,
                                            children: [
                                              Expanded(
                                                child: SizedBox(
                                                  child: Text(
                                                    '20% 이상',
                                                    textAlign: TextAlign.center,
                                                    style: TextStyle(
                                                      color: Colors.black,
                                                      fontSize: 5,
                                                      fontFamily: 'Inter',
                                                      fontWeight: FontWeight.w400,
                                                      height: 1,
                                                    ),
                                                  ),
                                                ),
                                              ),
                                            ],
                                          ),
                                        ),
                                      ),
                                    ],
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                      Expanded(
                        child: Container(
                          clipBehavior: Clip.antiAlias,
                          decoration: BoxDecoration(
                            color: Colors.white.withOpacity(0.00009999999747378752),
                          ),
                          child: Row(
                            mainAxisSize: MainAxisSize.min,
                            mainAxisAlignment: MainAxisAlignment.start,
                            crossAxisAlignment: CrossAxisAlignment.start,
                            children: [
                              Expanded(
                                child: Container(
                                  decoration: BoxDecoration(
                                    color: Colors.white.withOpacity(0.0020000000949949026),
                                    border: Border(
                                      left: BorderSide(width: 1, color: Color(0xFFB9B9B9)),
                                      top: BorderSide(width: 1, color: Color(0xFFB9B9B9)),
                                      right: BorderSide(color: Color(0xFFB9B9B9)),
                                      bottom: BorderSide(color: Color(0xFFB9B9B9)),
                                    ),
                                  ),
                                  child: Column(
                                    mainAxisSize: MainAxisSize.min,
                                    mainAxisAlignment: MainAxisAlignment.start,
                                    crossAxisAlignment: CrossAxisAlignment.start,
                                    children: [
                                      Expanded(
                                        child: Container(
                                          padding: const EdgeInsets.symmetric(horizontal: 12, vertical: 10),
                                          clipBehavior: Clip.antiAlias,
                                          decoration: BoxDecoration(),
                                          child: Row(
                                            mainAxisSize: MainAxisSize.min,
                                            mainAxisAlignment: MainAxisAlignment.start,
                                            crossAxisAlignment: CrossAxisAlignment.start,
                                            children: [
                                              Expanded(
                                                child: SizedBox(
                                                  child: Text(
                                                    '쓰가루(착색계) 및 이와 유사한 품종',
                                                    style: TextStyle(
                                                      color: Colors.black,
                                                      fontSize: 5,
                                                      fontFamily: 'Inter',
                                                      fontWeight: FontWeight.w400,
                                                      height:1,
                                                    ),
                                                  ),
                                                ),
                                              ),
                                            ],
                                          ),
                                        ),
                                      ),
                                    ],
                                  ),
                                ),
                              ),
                              Expanded(
                                child: Container(
                                  decoration: BoxDecoration(
                                    color: Colors.white.withOpacity(0.0020000000949949026),
                                    border: Border(
                                      left: BorderSide(width: 1, color: Color(0xFFB9B9B9)),
                                      top: BorderSide(width: 1, color: Color(0xFFB9B9B9)),
                                      right: BorderSide(color: Color(0xFFB9B9B9)),
                                      bottom: BorderSide(color: Color(0xFFB9B9B9)),
                                    ),
                                  ),
                                  child: Column(
                                    mainAxisSize: MainAxisSize.min,
                                    mainAxisAlignment: MainAxisAlignment.start,
                                    crossAxisAlignment: CrossAxisAlignment.start,
                                    children: [
                                      Expanded(
                                        child: Container(
                                          padding: const EdgeInsets.symmetric(horizontal: 12, vertical: 10),
                                          clipBehavior: Clip.antiAlias,
                                          decoration: BoxDecoration(),
                                          child: Row(
                                            mainAxisSize: MainAxisSize.min,
                                            mainAxisAlignment: MainAxisAlignment.start,
                                            crossAxisAlignment: CrossAxisAlignment.start,
                                            children: [
                                              Expanded(
                                                child: SizedBox(
                                                  child: Text(
                                                    '20% 이상',
                                                    textAlign: TextAlign.center,
                                                    style: TextStyle(
                                                      color: Colors.black,
                                                      fontSize: 5,
                                                      fontFamily: 'Inter',
                                                      fontWeight: FontWeight.w400,
                                                      height: 1,
                                                    ),
                                                  ),
                                                ),
                                              ),
                                            ],
                                          ),
                                        ),
                                      ),
                                    ],
                                  ),
                                ),
                              ),
                              Expanded(
                                child: Container(
                                  decoration: BoxDecoration(
                                    color: Colors.white.withOpacity(0.0020000000949949026),
                                    border: Border(
                                      left: BorderSide(width: 1, color: Color(0xFFB9B9B9)),
                                      top: BorderSide(width: 1, color: Color(0xFFB9B9B9)),
                                      right: BorderSide(color: Color(0xFFB9B9B9)),
                                      bottom: BorderSide(color: Color(0xFFB9B9B9)),
                                    ),
                                  ),
                                  child: Column(
                                    mainAxisSize: MainAxisSize.min,
                                    mainAxisAlignment: MainAxisAlignment.start,
                                    crossAxisAlignment: CrossAxisAlignment.start,
                                    children: [
                                      Expanded(
                                        child: Container(
                                          padding: const EdgeInsets.symmetric(horizontal: 12, vertical: 10),
                                          clipBehavior: Clip.antiAlias,
                                          decoration: BoxDecoration(),
                                          child: Row(
                                            mainAxisSize: MainAxisSize.min,
                                            mainAxisAlignment: MainAxisAlignment.start,
                                            crossAxisAlignment: CrossAxisAlignment.start,
                                            children: [
                                              Expanded(
                                                child: SizedBox(
                                                  child: Text(
                                                    '10% 이상',
                                                    textAlign: TextAlign.center,
                                                    style: TextStyle(
                                                      color: Colors.black,
                                                      fontSize: 5,
                                                      fontFamily: 'Inter',
                                                      fontWeight: FontWeight.w400,
                                                      height: 1,
                                                    ),
                                                  ),
                                                ),
                                              ),
                                            ],
                                          ),
                                        ),
                                      ),
                                    ],
                                  ),
                                ),
                              ),
                              Expanded(
                                child: Container(
                                  decoration: BoxDecoration(
                                    color: Colors.white.withOpacity(0.0020000000949949026),
                                    border: Border(
                                      left: BorderSide(width: 1, color: Color(0xFFB9B9B9)),
                                      top: BorderSide(width: 1, color: Color(0xFFB9B9B9)),
                                      right: BorderSide(color: Color(0xFFB9B9B9)),
                                      bottom: BorderSide(color: Color(0xFFB9B9B9)),
                                    ),
                                  ),
                                  child: Column(
                                    mainAxisSize: MainAxisSize.min,
                                    mainAxisAlignment: MainAxisAlignment.start,
                                    crossAxisAlignment: CrossAxisAlignment.start,
                                    children: [
                                      Expanded(
                                        child: Container(
                                          padding: const EdgeInsets.symmetric(horizontal: 12, vertical: 10),
                                          clipBehavior: Clip.antiAlias,
                                          decoration: BoxDecoration(),
                                          child: Row(
                                            mainAxisSize: MainAxisSize.min,
                                            mainAxisAlignment: MainAxisAlignment.start,
                                            crossAxisAlignment: CrossAxisAlignment.start,
                                            children: [
                                              Expanded(
                                                child: SizedBox(
                                                  child: Text(
                                                    '-',
                                                    textAlign: TextAlign.center,
                                                    style: TextStyle(
                                                      color: Colors.black,
                                                      fontSize: 5,
                                                      fontFamily: 'Inter',
                                                      fontWeight: FontWeight.w400,
                                                      height: 1,
                                                    ),
                                                  ),
                                                ),
                                              ),
                                            ],
                                          ),
                                        ),
                                      ),
                                    ],
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 17,
                top: 171,
                child: Container(
                  width: 342,
                  
                  clipBehavior: Clip.antiAlias,
                  decoration: ShapeDecoration(
                    color: Colors.white,
                    shape: RoundedRectangleBorder(
                      side: BorderSide(width: 1, color: Color(0xFFB9B9B9)),
                      borderRadius: BorderRadius.circular(4),
                    ),
                  ),
                  child: Column(
                    mainAxisSize: MainAxisSize.min,
                    mainAxisAlignment: MainAxisAlignment.start,
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      Container(
                        
                        clipBehavior: Clip.antiAlias,
                        decoration: BoxDecoration(
                          color: Colors.white.withOpacity(0.00009999999747378752),
                        ),
                        child: Row(
                          mainAxisSize: MainAxisSize.min,
                          mainAxisAlignment: MainAxisAlignment.start,
                          crossAxisAlignment: CrossAxisAlignment.start,
                          children: [
                            Expanded(
                              child: Container(
                                decoration: BoxDecoration(
                                  color: Colors.black.withOpacity(0.05999999865889549),
                                  border: Border(
                                    left: BorderSide(width: 1, color: Color(0xFFB9B9B9)),
                                    top: BorderSide(width: 1, color: Color(0xFFB9B9B9)),
                                    right: BorderSide(color: Color(0xFFB9B9B9)),
                                    bottom: BorderSide(color: Color(0xFFB9B9B9)),
                                  ),
                                ),
                                child: Column(
                                  mainAxisSize: MainAxisSize.min,
                                  mainAxisAlignment: MainAxisAlignment.start,
                                  crossAxisAlignment: CrossAxisAlignment.start,
                                  children: [
                                    Container(
                                      padding: const EdgeInsets.symmetric(horizontal: 12, vertical: 10),
                                      clipBehavior: Clip.antiAlias,
                                      decoration: BoxDecoration(),
                                      child: Row(
                                        mainAxisSize: MainAxisSize.min,
                                        mainAxisAlignment: MainAxisAlignment.start,
                                        crossAxisAlignment: CrossAxisAlignment.start,
                                        children: [
                                          Expanded(
                                            child: SizedBox(
                                              child: Text(
                                                '',
                                                textAlign: TextAlign.center,
                                                style: TextStyle(
                                                  color: Colors.black,
                                                  fontSize: 7,
                                                  fontFamily: 'Inter',
                                                  fontWeight: FontWeight.w600,
                                                  height: 1,
                                                ),
                                              ),
                                            ),
                                          ),
                                        ],
                                      ),
                                    ),
                                  ],
                                ),
                              ),
                            ),
                            Expanded(
                              child: Container(
                                decoration: BoxDecoration(
                                  color: Colors.black.withOpacity(0.05999999865889549),
                                  border: Border(
                                    left: BorderSide(width: 1, color: Color(0xFFB9B9B9)),
                                    top: BorderSide(width: 1, color: Color(0xFFB9B9B9)),
                                    right: BorderSide(color: Color(0xFFB9B9B9)),
                                    bottom: BorderSide(color: Color(0xFFB9B9B9)),
                                  ),
                                ),
                                child: Column(
                                  mainAxisSize: MainAxisSize.min,
                                  mainAxisAlignment: MainAxisAlignment.start,
                                  crossAxisAlignment: CrossAxisAlignment.start,
                                  children: [
                                    Container(
                                      padding: const EdgeInsets.symmetric(horizontal: 12, vertical: 10),
                                      clipBehavior: Clip.antiAlias,
                                      decoration: BoxDecoration(),
                                      child: Row(
                                        mainAxisSize: MainAxisSize.min,
                                        mainAxisAlignment: MainAxisAlignment.start,
                                        crossAxisAlignment: CrossAxisAlignment.start,
                                        children: [
                                          Expanded(
                                            child: SizedBox(
                                              child: Text(
                                                '3L',
                                                textAlign: TextAlign.center,
                                                style: TextStyle(
                                                  color: Colors.black,
                                                  fontSize: 7,
                                                  fontFamily: 'Inter',
                                                  fontWeight: FontWeight.w600,
                                                  height: 1,
                                                ),
                                              ),
                                            ),
                                          ),
                                        ],
                                      ),
                                    ),
                                  ],
                                ),
                              ),
                            ),
                            Expanded(
                              child: Container(
                                decoration: BoxDecoration(
                                  color: Colors.black.withOpacity(0.05999999865889549),
                                  border: Border(
                                    left: BorderSide(width: 1, color: Color(0xFFB9B9B9)),
                                    top: BorderSide(width: 1, color: Color(0xFFB9B9B9)),
                                    right: BorderSide(color: Color(0xFFB9B9B9)),
                                    bottom: BorderSide(color: Color(0xFFB9B9B9)),
                                  ),
                                ),
                                child: Column(
                                  mainAxisSize: MainAxisSize.min,
                                  mainAxisAlignment: MainAxisAlignment.start,
                                  crossAxisAlignment: CrossAxisAlignment.start,
                                  children: [
                                    Container(
                                      padding: const EdgeInsets.symmetric(horizontal: 12, vertical: 10),
                                      clipBehavior: Clip.antiAlias,
                                      decoration: BoxDecoration(),
                                      child: Row(
                                        mainAxisSize: MainAxisSize.min,
                                        mainAxisAlignment: MainAxisAlignment.start,
                                        crossAxisAlignment: CrossAxisAlignment.start,
                                        children: [
                                          Expanded(
                                            child: SizedBox(
                                              child: Text(
                                                '2L',
                                                textAlign: TextAlign.center,
                                                style: TextStyle(
                                                  color: Colors.black,
                                                  fontSize: 7,
                                                  fontFamily: 'Inter',
                                                  fontWeight: FontWeight.w600,
                                                  height: 1,
                                                ),
                                              ),
                                            ),
                                          ),
                                        ],
                                      ),
                                    ),
                                  ],
                                ),
                              ),
                            ),
                            Expanded(
                              child: Container(
                                decoration: BoxDecoration(
                                  color: Colors.black.withOpacity(0.05999999865889549),
                                  border: Border(
                                    left: BorderSide(width: 1, color: Color(0xFFB9B9B9)),
                                    top: BorderSide(width: 1, color: Color(0xFFB9B9B9)),
                                    right: BorderSide(color: Color(0xFFB9B9B9)),
                                    bottom: BorderSide(color: Color(0xFFB9B9B9)),
                                  ),
                                ),
                                child: Column(
                                  mainAxisSize: MainAxisSize.min,
                                  mainAxisAlignment: MainAxisAlignment.start,
                                  crossAxisAlignment: CrossAxisAlignment.start,
                                  children: [
                                    Container(
                                      padding: const EdgeInsets.symmetric(horizontal: 12, vertical: 10),
                                      clipBehavior: Clip.antiAlias,
                                      decoration: BoxDecoration(),
                                      child: Row(
                                        mainAxisSize: MainAxisSize.min,
                                        mainAxisAlignment: MainAxisAlignment.start,
                                        crossAxisAlignment: CrossAxisAlignment.start,
                                        children: [
                                          Expanded(
                                            child: SizedBox(
                                              child: Text(
                                                'L',
                                                textAlign: TextAlign.center,
                                                style: TextStyle(
                                                  color: Colors.black,
                                                  fontSize: 7,
                                                  fontFamily: 'Inter',
                                                  fontWeight: FontWeight.w600,
                                                  height: 1,
                                                ),
                                              ),
                                            ),
                                          ),
                                        ],
                                      ),
                                    ),
                                  ],
                                ),
                              ),
                            ),
                            Expanded(
                              child: Container(
                                decoration: BoxDecoration(
                                  color: Colors.black.withOpacity(0.05999999865889549),
                                  border: Border(
                                    left: BorderSide(width: 1, color: Color(0xFFB9B9B9)),
                                    top: BorderSide(width: 1, color: Color(0xFFB9B9B9)),
                                    right: BorderSide(color: Color(0xFFB9B9B9)),
                                    bottom: BorderSide(color: Color(0xFFB9B9B9)),
                                  ),
                                ),
                                child: Column(
                                  mainAxisSize: MainAxisSize.min,
                                  mainAxisAlignment: MainAxisAlignment.start,
                                  crossAxisAlignment: CrossAxisAlignment.start,
                                  children: [
                                    Container(
                                      padding: const EdgeInsets.symmetric(horizontal: 12, vertical: 10),
                                      clipBehavior: Clip.antiAlias,
                                      decoration: BoxDecoration(),
                                      child: Row(
                                        mainAxisSize: MainAxisSize.min,
                                        mainAxisAlignment: MainAxisAlignment.start,
                                        crossAxisAlignment: CrossAxisAlignment.start,
                                        children: [
                                          Expanded(
                                            child: SizedBox(
                                              child: Text(
                                                'M',
                                                textAlign: TextAlign.center,
                                                style: TextStyle(
                                                  color: Colors.black,
                                                  fontSize: 7,
                                                  fontFamily: 'Inter',
                                                  fontWeight: FontWeight.w600,
                                                  height:1,
                                                ),
                                              ),
                                            ),
                                          ),
                                        ],
                                      ),
                                    ),
                                  ],
                                ),
                              ),
                            ),
                            Expanded(
                              child: Container(
                                decoration: BoxDecoration(
                                  color: Colors.black.withOpacity(0.05999999865889549),
                                  border: Border(
                                    left: BorderSide(width: 1, color: Color(0xFFB9B9B9)),
                                    top: BorderSide(width: 1, color: Color(0xFFB9B9B9)),
                                    right: BorderSide(color: Color(0xFFB9B9B9)),
                                    bottom: BorderSide(color: Color(0xFFB9B9B9)),
                                  ),
                                ),
                                child: Column(
                                  mainAxisSize: MainAxisSize.min,
                                  mainAxisAlignment: MainAxisAlignment.start,
                                  crossAxisAlignment: CrossAxisAlignment.start,
                                  children: [
                                    Container(
                                      padding: const EdgeInsets.symmetric(horizontal: 12, vertical: 10),
                                      clipBehavior: Clip.antiAlias,
                                      decoration: BoxDecoration(),
                                      child: Row(
                                        mainAxisSize: MainAxisSize.min,
                                        mainAxisAlignment: MainAxisAlignment.start,
                                        crossAxisAlignment: CrossAxisAlignment.start,
                                        children: [
                                          Expanded(
                                            child: SizedBox(
                                              child: Text(
                                                'S',
                                                textAlign: TextAlign.center,
                                                style: TextStyle(
                                                  color: Colors.black,
                                                  fontSize: 7,
                                                  fontFamily: 'Inter',
                                                  fontWeight: FontWeight.w600,
                                                  height: 1,
                                                ),
                                              ),
                                            ),
                                          ),
                                        ],
                                      ),
                                    ),
                                  ],
                                ),
                              ),
                            ),
                            Expanded(
                              child: Container(
                                decoration: BoxDecoration(
                                  color: Colors.black.withOpacity(0.05999999865889549),
                                  border: Border(
                                    left: BorderSide(width: 1, color: Color(0xFFB9B9B9)),
                                    top: BorderSide(width: 1, color: Color(0xFFB9B9B9)),
                                    right: BorderSide(color: Color(0xFFB9B9B9)),
                                    bottom: BorderSide(color: Color(0xFFB9B9B9)),
                                  ),
                                ),
                                child: Column(
                                  mainAxisSize: MainAxisSize.min,
                                  mainAxisAlignment: MainAxisAlignment.start,
                                  crossAxisAlignment: CrossAxisAlignment.start,
                                  children: [
                                    Container(
                                      padding: const EdgeInsets.symmetric(horizontal: 12, vertical: 10),
                                      clipBehavior: Clip.antiAlias,
                                      decoration: BoxDecoration(),
                                      child: Row(
                                        mainAxisSize: MainAxisSize.min,
                                        mainAxisAlignment: MainAxisAlignment.start,
                                        crossAxisAlignment: CrossAxisAlignment.start,
                                        children: [
                                          Expanded(
                                            child: SizedBox(
                                              child: Text(
                                                '2S',
                                                textAlign: TextAlign.center,
                                                style: TextStyle(
                                                  color: Colors.black,
                                                  fontSize: 7,
                                                  fontFamily: 'Inter',
                                                  fontWeight: FontWeight.w600,
                                                  height: 1,
                                                ),
                                              ),
                                            ),
                                          ),
                                        ],
                                      ),
                                    ),
                                  ],
                                ),
                              ),
                            ),
                          ],
                        ),
                      ),
                      Container(
                        height: 29,
                        clipBehavior: Clip.antiAlias,
                        decoration: BoxDecoration(
                          color: Colors.white.withOpacity(0.00009999999747378752),
                        ),
                        child: Row(
                          
                          children: [
                            Expanded(
                              child: Container(
                                decoration: BoxDecoration(
                                  color: Colors.white.withOpacity(0.0020000000949949026),
                                  border: Border(
                                    left: BorderSide(width: 1, color: Color(0xFFB9B9B9)),
                                    top: BorderSide(width: 1, color: Color(0xFFB9B9B9)),
                                    right: BorderSide(color: Color(0xFFB9B9B9)),
                                    bottom: BorderSide(color: Color(0xFFB9B9B9)),
                                  ),
                                ),
                                child: Column(
                                  
                                  children: [
                                    Container(
                                      padding: const EdgeInsets.all(3),
                                      clipBehavior: Clip.antiAlias,
                                      decoration: BoxDecoration(),
                                      child: Row(
                                        
                                        children: [
                                          Expanded(
                                            child: SizedBox(
                                              child: Text(
                                                'g/개',
                                                style: TextStyle(
                                                  color: Colors.black,
                                                  fontSize: 5,
                                                  fontFamily: 'Inter',
                                                  fontWeight: FontWeight.w400,
                                                  height: 1,
                                                ),
                                              ),
                                            ),
                                          ),
                                        ],
                                      ),
                                    ),
                                  ],
                                ),
                              ),
                            ),
                            Expanded(
                              child: Container(
                                decoration: BoxDecoration(
                                  color: Colors.white.withOpacity(0.0020000000949949026),
                                  border: Border(
                                    left: BorderSide(width: 1, color: Color(0xFFB9B9B9)),
                                    top: BorderSide(width: 1, color: Color(0xFFB9B9B9)),
                                    right: BorderSide(color: Color(0xFFB9B9B9)),
                                    bottom: BorderSide(color: Color(0xFFB9B9B9)),
                                  ),
                                ),
                                child: Column(
                                  
                                  children: [
                                    Container(
                                      padding: const EdgeInsets.all(3),
                                      clipBehavior: Clip.antiAlias,
                                      decoration: BoxDecoration(),
                                      child: Row(
                                        
                                        children: [
                                          Expanded(
                                            child: SizedBox(
                                              child: Text(
                                                '375이상',
                                                style: TextStyle(
                                                  color: Colors.black,
                                                  fontSize: 5,
                                                  fontFamily: 'Inter',
                                                  fontWeight: FontWeight.w400,
                                                  height: 1,
                                                ),
                                              ),
                                            ),
                                          ),
                                        ],
                                      ),
                                    ),
                                  ],
                                ),
                              ),
                            ),
                            Expanded(
                              child: Container(
                                decoration: BoxDecoration(
                                  color: Colors.white.withOpacity(0.0020000000949949026),
                                  border: Border(
                                    left: BorderSide(width: 1, color: Color(0xFFB9B9B9)),
                                    top: BorderSide(width: 1, color: Color(0xFFB9B9B9)),
                                    right: BorderSide(color: Color(0xFFB9B9B9)),
                                    bottom: BorderSide(color: Color(0xFFB9B9B9)),
                                  ),
                                ),
                                child: Column(
                                  
                                  children: [
                                    Container(
                                      padding: const EdgeInsets.all(3),
                                      clipBehavior: Clip.antiAlias,
                                      decoration: BoxDecoration(),
                                      child: Row(
                                        
                                        children: [
                                          Expanded(
                                            child: SizedBox(
                                              child: Text(
                                                '300이상 ~ 375 미만',
                                                style: TextStyle(
                                                  color: Colors.black,
                                                  fontSize: 5,
                                                  fontFamily: 'Inter',
                                                  fontWeight: FontWeight.w400,
                                                  height: 1,
                                                ),
                                              ),
                                            ),
                                          ),
                                        ],
                                      ),
                                    ),
                                  ],
                                ),
                              ),
                            ),
                            Expanded(
                              child: Container(
                                decoration: BoxDecoration(
                                  color: Colors.white.withOpacity(0.0020000000949949026),
                                  border: Border(
                                    left: BorderSide(width: 1, color: Color(0xFFB9B9B9)),
                                    top: BorderSide(width: 1, color: Color(0xFFB9B9B9)),
                                    right: BorderSide(color: Color(0xFFB9B9B9)),
                                    bottom: BorderSide(color: Color(0xFFB9B9B9)),
                                  ),
                                ),
                                child: Column(
                                  
                                  children: [
                                    Container(
                                      padding: const EdgeInsets.all(3),
                                      clipBehavior: Clip.antiAlias,
                                      decoration: BoxDecoration(),
                                      child: Row(
                                        
                                        children: [
                                          Expanded(
                                            child: SizedBox(
                                              child: Text(
                                                '250 이상 ~ 300 미만',
                                                style: TextStyle(
                                                  color: Colors.black,
                                                  fontSize: 5,
                                                  fontFamily: 'Inter',
                                                  fontWeight: FontWeight.w400,
                                                  height: 1,
                                                ),
                                              ),
                                            ),
                                          ),
                                        ],
                                      ),
                                    ),
                                  ],
                                ),
                              ),
                            ),
                            Expanded(
                              child: Container(
                                decoration: BoxDecoration(
                                  color: Colors.white.withOpacity(0.0020000000949949026),
                                  border: Border(
                                    left: BorderSide(width: 1, color: Color(0xFFB9B9B9)),
                                    top: BorderSide(width: 1, color: Color(0xFFB9B9B9)),
                                    right: BorderSide(color: Color(0xFFB9B9B9)),
                                    bottom: BorderSide(color: Color(0xFFB9B9B9)),
                                  ),
                                ),
                                child: Column(
                                  
                                  children: [
                                    Container(
                                      padding: const EdgeInsets.all(3),
                                      clipBehavior: Clip.antiAlias,
                                      decoration: BoxDecoration(),
                                      child: Row(
                                        
                                        children: [
                                          Expanded(
                                            child: SizedBox(
                                              child: Text(
                                                '214 이상 ~ 250 미만',
                                                style: TextStyle(
                                                  color: Colors.black,
                                                  fontSize: 5,
                                                  fontFamily: 'Inter',
                                                  fontWeight: FontWeight.w400,
                                                  height: 1,
                                                ),
                                              ),
                                            ),
                                          ),
                                        ],
                                      ),
                                    ),
                                  ],
                                ),
                              ),
                            ),
                            Expanded(
                              child: Container(
                                decoration: BoxDecoration(
                                  color: Colors.white.withOpacity(0.0020000000949949026),
                                  border: Border(
                                    left: BorderSide(width: 1, color: Color(0xFFB9B9B9)),
                                    top: BorderSide(width: 1, color: Color(0xFFB9B9B9)),
                                    right: BorderSide(color: Color(0xFFB9B9B9)),
                                    bottom: BorderSide(color: Color(0xFFB9B9B9)),
                                  ),
                                ),
                                child: Column(
                                  
                                  children: [
                                    Container(
                                      padding: const EdgeInsets.all(3),
                                      clipBehavior: Clip.antiAlias,
                                      decoration: BoxDecoration(),
                                      child: Row(
                                        
                                        children: [
                                          Expanded(
                                            child: SizedBox(
                                              child: Text(
                                                '188 이상 ~ 214 미만',
                                                style: TextStyle(
                                                  color: Colors.black,
                                                  fontSize: 5,
                                                  fontFamily: 'Inter',
                                                  fontWeight: FontWeight.w400,
                                                  height: 1,
                                                ),
                                              ),
                                            ),
                                          ),
                                        ],
                                      ),
                                    ),
                                  ],
                                ),
                              ),
                            ),
                            Expanded(
                              child: Container(
                                decoration: BoxDecoration(
                                  color: Colors.white.withOpacity(0.0020000000949949026),
                                  border: Border(
                                    left: BorderSide(width: 1, color: Color(0xFFB9B9B9)),
                                    top: BorderSide(width: 1, color: Color(0xFFB9B9B9)),
                                    right: BorderSide(color: Color(0xFFB9B9B9)),
                                    bottom: BorderSide(color: Color(0xFFB9B9B9)),
                                  ),
                                ),
                                child: Column(
                                  
                                  children: [
                                    Container(
                                      padding: const EdgeInsets.all(3),
                                      clipBehavior: Clip.antiAlias,
                                      decoration: BoxDecoration(),
                                      child: Row(
                                        
                                        children: [
                                          Expanded(
                                            child: SizedBox(
                                              child: Text(
                                                '167 이상 ~ 188 미만',
                                                style: TextStyle(
                                                  color: Colors.black,
                                                  fontSize: 5,
                                                  fontFamily: 'Inter',
                                                  fontWeight: FontWeight.w400,
                                                  height: 1,
                                                ),
                                              ),
                                            ),
                                          ),
                                        ],
                                      ),
                                    ),
                                  ],
                                ),
                              ),
                            ),
                          ],
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 140,
                top: 102,
                child: Text(
                  '사과 등급',
                  textAlign: TextAlign.center,
                  style: TextStyle(
                    color: Colors.black,
                    fontSize: 24,
                    fontFamily: 'Inter',
                    fontWeight: FontWeight.w600,
                    height: 1,
                    letterSpacing: -0.24,
                  ),
                ),
              ),
            ],
          ),
        ),
      ],
    );
  }
}