import 'package:flutter/material.dart';
import 'food.dart';
void main() {
  runApp(const Soup1());
}

// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class Soup1 extends StatelessWidget {
  const Soup1({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: const Color.fromARGB(255, 18, 32, 47),
      ),
      home: Scaffold(
        body: ListView(
          children: [
            Soup(), // Add this line to include the CustomContent widget
          ],
        ),
      ),
    );
  }
}

class Soup extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Container(
          width: 375,
          height: 812,
          clipBehavior: Clip.antiAlias,
          decoration: BoxDecoration(color: Colors.white),
          child: Stack(
            children: [
              Align(
          alignment: Alignment.topLeft,
          
          child: Padding(
            padding: const EdgeInsets.all(15.0),
            child: ElevatedButton(
              onPressed: () {
                    Navigator.push(
                      context,
                      MaterialPageRoute(builder: (context) => Food1()),
                    );
                  },
              child: const Text('이전'),
            ),
          ),
        ),
              Positioned(
                left: 1,
                top: 373,
                child: Container(
                  width: 375,
                  height: 349,
                  child: const Column(
                    mainAxisSize: MainAxisSize.min,
                    mainAxisAlignment: MainAxisAlignment.start,
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      SizedBox(
                        
                        child: Text(
                          '재료 : 사과, 양파, 올리브유, 우유, 치즈, 소금, 물',
                          style: TextStyle(
                            color: Colors.black,
                            fontSize: 12,
                            fontFamily: 'Inter',
                            fontWeight: FontWeight.w400,
                            height: 0.12,
                          ),
                        ),
                      ),
                      SizedBox(height: 24),
                      Text.rich(
                        TextSpan(
                          children: [
                            TextSpan(
                              text: '만드는 방법 : \n',
                              style: TextStyle(
                                color: Colors.black,
                                fontSize: 10,
                                fontFamily: 'Inter',
                                fontWeight: FontWeight.w500,
                              ),
                            ),
                              TextSpan(
                                text:
                                    '뚜껑으로 사용할 사과 윗부분은 적당한 두께로 썰어준다.\n사과를 스프컵으로 사용하기 위해 사과껍질이 벗겨지지 않도록 속을 파낸다.\n양파는 채를 썰어 준비한다.\n달군 냄비에 올리브유를 두르고 양파를 넣어 갈색빛이 나도록 볶는다.\n물과 함께 파낸 사과 속을 넣어 한 번 더 볶는다.\n양파와 사과가 모두 익으면 믹서기에 넣어 곱게 갈아준다.\n냄비에 다시 부어 우유와 치즈를 넣고 저어가면서 끓인다.\n취향에 따라 소금으로 간한다.\n완성된 스프는 준비한 사과 컵에 담아 완성한다.',
                                style: TextStyle(
                                  color: Colors.black,
                                  fontSize: 10,
                                  fontFamily: 'Inter',
                                  fontWeight: FontWeight.w500,
                                  height: 1,
                                ),
                              ),
                            ],
                          ),
                        ),
                      
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 1,
                top: 87,
                child: SizedBox(
                  width: 375,
                  child: Text(
                    '사과스프',
                    textAlign: TextAlign.center,
                    style: TextStyle(
                      color: Colors.black,
                      fontSize: 24,
                      fontFamily: 'Inter',
                      fontWeight: FontWeight.w700,
                      height: 0,
                      letterSpacing: -0.48,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 14,
                top: 159,
                child: Container(
                  width: 345,
                  height: 200,
                  clipBehavior: Clip.antiAlias,
                  decoration: ShapeDecoration(
                    image: DecorationImage(
                      image: AssetImage('assets/images/tmvm.jpg'),
                      fit: BoxFit.fill,
                    ),
                    shape: RoundedRectangleBorder(
                        borderRadius: BorderRadius.circular(8)),
                  ),
                ),
              ),
            ],
          ),
        ),
      ],
    );
  }
}
