import 'package:flutter/material.dart';
import 'food.dart';

void main() {
  runApp(const Tea1());
}

// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class Tea1 extends StatelessWidget {
  const Tea1({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: const Color.fromARGB(255, 18, 32, 47),
      ),
      home: Scaffold( 
        body: ListView(
          children: [
            Tea(), // Add this line to include the CustomContent widget
          ],
        ),
      ),
    );
  }
}


class Tea extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Container(
          width: 375,
          height: 812,
          clipBehavior: Clip.antiAlias,
          decoration: BoxDecoration(color: Colors.white),
          child: Stack(
            children: [
              Align(
          alignment: Alignment.topLeft,
          
          child: Padding(
            padding: const EdgeInsets.all(15.0),
            child: ElevatedButton(
              onPressed: () {
                    Navigator.push(
                      context,
                      MaterialPageRoute(builder: (context) => Food1()),
                    );
                  },
              child: const Text('이전'),
            ),
          ),
        ),
              Positioned(
                left: 1,
                top: 373,
                child: Container(
                  width: 375,
                  height: 349,
                  child: const Column(
                    mainAxisSize: MainAxisSize.min,
                    mainAxisAlignment: MainAxisAlignment.start,
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      SizedBox(
                        
                        child: Text(
                          '재료 : 사과, 꿀',
                          style: TextStyle(
                            color: Colors.black,
                            fontSize: 12,
                            fontFamily: 'Inter',
                            fontWeight: FontWeight.w400,
                            height: 0.12,
                          ),
                        ),
                      ),
                       SizedBox(height: 24),
                      Text.rich(
                        TextSpan(
                          children: [
                            TextSpan(
                              text: '만드는 방법 : \n',
                              style: TextStyle(
                                color: Colors.black,
                                fontSize: 10,
                                fontFamily: 'Inter',
                                fontWeight: FontWeight.w500,
                              ),
                            ),
                              TextSpan(
                                text: '사과씨를 제거하고 얇게 썰어 소독된 병에 넣어준다\n사과가 잠길 정도로 꿀을 넣고 뚜껑을 덮어 4일 정 숙성시켜준다.\n따뜻한 물과 섞어 마시면 된다.',
                                style: TextStyle(
                                  color: Colors.black,
                                  fontSize: 10,
                                  fontFamily: 'Inter',
                                  fontWeight: FontWeight.w500,
                                  height: 1,
                                ),
                              ),
                            ],
                          ),
                        ),
                      
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 1,
                top: 87,
                child: SizedBox(
                  width: 375,
                  child: Text(
                    '사과차',
                    textAlign: TextAlign.center,
                    style: TextStyle(
                      color: Colors.black,
                      fontSize: 24,
                      fontFamily: 'Inter',
                      fontWeight: FontWeight.w700,
                      height: 0,
                      letterSpacing: -0.48,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 14,
                top: 159,
                child: Container(
                  width: 345,
                  height: 200,
                  clipBehavior: Clip.antiAlias,
                  decoration: ShapeDecoration(
                    image: DecorationImage(
                      image: AssetImage('assets/images/차.jpg'),
                      fit: BoxFit.fill,
                    ),
                    shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(8)),
                  ),
                ),
              ),
            ],
          ),
        ),
      ],
    );
  }
}
